# ETL del archivo en crudo `movies_dataset.parquet`

## Librerías

In [1]:
import os
import ast
import gc

import pandas as pd

## Extracción

In [2]:
url = "https://github.com/FranciscoHugoLezik/Movies_data/blob/main/movies_dataset.parquet?raw=true"

movies = pd.read_parquet(
    url, 
    engine="fastparquet")

In [3]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,None,Toy Story,False,7.7,5415
1,False,None,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",None,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",None,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92
3,False,None,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",None,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",None,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173

La columna 'id' esta completa.

In [4]:
movies['id'].isnull().sum()

0

## Tranformación

### Borrar duplicados en la columna 'id'

Hay valores duplicados en la columna 'id'.

In [5]:
movies['id'].duplicated(
    keep='first').sum()

30

Se eliminan los duplicados.

In [6]:
movies.drop_duplicates(
    subset='id', 
    inplace=True
    )

Hay valores únicos.

In [7]:
movies['id'].duplicated(
    keep='first').sum()

0

### Renombrar el nombre de la columna 'id' por 'movie_id'

Se hace esto porque para, mas adelante, poder hacer un join con los dataset 'cast.parquet' y 'crew.parquet'.

In [8]:
movies.rename(
    columns={'id': 'movie_id'}, 
    inplace=True)

Se cambio el nombre.

In [9]:
'id' not in movies.columns

True

In [10]:
'movie_id' in movies.columns

True

### Crear y explorar el dataframe 'genres'

Se crea un nuevo dataframe con las columnas 'genres' y 'movie_id'.

In [11]:
genres = movies[[
  'genres', 
  'movie_id'
  ]].copy()

Valor en la columna 'genres' de la primera fila. Es una cadena con la forma de una lista de diccionarios.

In [12]:
genres['genres'].iloc[0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

La columna 'genres' esta completa.

In [13]:
genres['genres'].isnull().sum()

0

### Desanidar la columna 'genres'

Se convierte a las cadenas en listas de diccionarios.

In [14]:
genres['genres'] = genres['genres'].apply(
    ast.literal_eval)

Se separan los elementos de las listas en filas.

In [15]:
genres_en_filas = genres.explode('genres')

Se convierten las llaves en columnas.

In [16]:
genres_en_columnas = pd.json_normalize(
    genres_en_filas['genres'])

### Crear un nuevo dataframe 'genres'

Se crea un dataframe con la columna 'movie_id' junto con las nuevas columnas.

In [17]:
genres = genres_en_filas.drop(
    columns='genres').join(
        genres_en_columnas)

Se eliminan los siguientes objetos para liberar memoria.

In [18]:
del genres_en_filas
del genres_en_columnas
gc.collect()

154

Se agrupa por la columna 'movie_id'

In [19]:
genres = genres.groupby('movie_id').agg(
    {'name': list}).reset_index()

### Exploración de 'genres'

Se explora el dataframe.

In [20]:
genres

      movie_id                            name
0          100                [Comedy, Comedy]
1        10000              [Mystery, Mystery]
2        10001                [Action, Action]
3       100010              [Mystery, Mystery]
4       100017                         [Drama]
...        ...                             ...
45431    99946                         [Music]
45432     9995  [Thriller, Thriller, Thriller]
45433     9997    [Drama, Drama, Drama, Drama]
45434    99977                       [Romance]
45435     9999                  [Drama, Drama]

[45436 rows x 2 columns]

Primera fila.

In [21]:
genres.iloc[0]

movie_id                 100
name        [Comedy, Comedy]
Name: 0, dtype: object

In [22]:
genres['name'].isnull().sum()

0

### Renombrar la columna 'name'

Se renombra la columna 'name' por 'genres'.

In [23]:
genres.rename(
    columns={'name': 'genres'}, 
    inplace=True)

Se cambio el nombre.

In [24]:
genres.columns

Index(['movie_id', 'genres'], dtype='object')

### Eliminar las columnas innecesarias de 'movies'

Se van a eliminar columnas que no aportan a los objetivos del proyecto.

Columnas innecesarias.

In [25]:
innecesarias = [
    "video", 
    "imdb_id", 
    "adult", 
    "original_title", 
    "poster_path", 
    "homepage", 
    "belongs_to_collection", 
    "genres", 
    "production_companies", 
    "production_countries", 
    "spoken_languages"
    ]

Las columnas innecesarias son eliminadas.

In [26]:
movies.drop(
    columns=innecesarias, 
    inplace=True
    )

Las columnas innecesarias estan eliminadas.

In [27]:
set(movies.columns).isdisjoint(set(innecesarias))

True

Se ven las columnas que quedan.

In [28]:
for columna in movies.columns:
    print(columna)

budget
movie_id
original_language
overview
popularity
release_date
revenue
runtime
status
tagline
title
vote_average
vote_count

### Unir 'movies' con 'genres'

In [29]:
movies = pd.merge(
    movies, 
    genres, 
    how='inner', 
    on='movie_id'
    )

In [30]:
del genres
gc.collect()

0

### Eliminar los nulos de la columna 'title'

Hay nulos en la columna 'title'.

In [31]:
movies['title'].isnull().sum()

6

Se eliminan los nulos.

In [32]:
movies.dropna(
    subset='title', 
    inplace=True)

Los nulos están eliminados.

In [33]:
movies['release_date'].isnull().sum()

84

### Eliminar nulos en la columna 'release_date'

Hay nulos en la columna 'release_date'.

In [34]:
movies['release_date'].isnull().sum()

84

Se eliminan los nulos.

In [35]:
movies.dropna(
    subset='release_date', 
    inplace=True)

Los nulos están eliminados.

In [36]:
movies['release_date'].isnull().sum()

0

### Dar formato AAAA-mm-dd a la columna 'release_date'

Se asegura que todas las fechas tengan el formato deseado:

In [38]:
movies['release_date'] = pd.to_datetime(
    movies['release_date']).dt.strftime(
        '%Y-%m-%d')

### Cambiar los tipos de algunas columnas

Se cambian porque se van a hacer operaciones numericas con varias columnas y una columna es de tipo fecha.

Tipos de las columnas.

In [40]:
movies.dtypes

budget               object
movie_id             object
original_language    object
overview             object
popularity           object
release_date         object
revenue              object
runtime              object
status               object
tagline              object
title                object
vote_average         object
vote_count           object
genres               object
dtype: object

* Columna 'budget'.

In [41]:
movies['budget'].dtype

dtype('O')

In [42]:
movies['budget'] = movies['budget'].astype(
    'int64')

In [43]:
movies['budget'].dtype

dtype('int64')

* Columna 'popularity'.

In [44]:
movies['popularity'].dtype

dtype('O')

In [45]:
movies['popularity'] = movies['popularity'].astype(
    'float64')

In [46]:
movies['popularity'].dtype

dtype('float64')

* Columna 'revenue'.

In [47]:
movies['revenue'].dtype

dtype('O')

In [48]:
movies['revenue'] = movies['revenue'].astype(
    'int64')

In [49]:
movies['revenue'].dtype

dtype('int64')

* Columna 'runtime'.

In [50]:
movies['runtime'].dtype

dtype('O')

In [51]:
movies['runtime'] = movies['runtime'].astype(
    'float64')

In [52]:
movies['runtime'].dtype

dtype('float64')

* Columna 'vote_average'.

In [53]:
movies['vote_average'].dtype

dtype('O')

In [54]:
movies['vote_average'] = movies['vote_average'].astype(
    'float64')

In [55]:
movies['vote_average'].dtype

dtype('float64')

* Columna 'vote_count'.

In [56]:
movies['vote_count'].dtype

dtype('O')

In [57]:
movies['vote_count'] = movies['vote_count'].astype(
    'int64')

In [58]:
movies['vote_count'].dtype

dtype('int64')

Tipos de las columnas.

In [59]:
movies.dtypes

budget                 int64
movie_id              object
original_language     object
overview              object
popularity           float64
release_date          object
revenue                int64
runtime              float64
status                object
tagline               object
title                 object
vote_average         float64
vote_count             int64
genres                object
dtype: object

### Rellenar con cero los valores nulos en las columnas 'revenue' y 'budget'

Columna 'revenue'.

In [60]:
movies['revenue'].isnull().sum()

0

In [61]:
movies['revenue'] = movies['revenue'].fillna(0)

Columna 'budget'.

In [62]:
movies['budget'].isnull().sum()

0

In [63]:
movies['budget'] = movies['budget'].fillna(0)

### Eliminar los nulos de la columna 'release_date'

Hay nulos en la columna 'release_date'.

In [64]:
movies['release_date'].isnull().sum()

0

Se eliminan los nulos.

In [65]:
movies.dropna(
    subset='release_date', 
    inplace=True)

Los nulos están eliminados.

In [66]:
movies['release_date'].isnull().sum()

0

### Crear la columna 'release_year'

Se extrae el año de la columna 'release_date' en la nueva columna 'release_year'.

In [67]:
movies['release_year'] = pd.to_datetime(
    movies['release_date']
    ).dt.year.astype(str)

El año fue extraído correctamente.

In [68]:
movies.iloc[0]['release_year']

'1995'

### Crear la columna 'return'

Gran parte de los datos son cero en las columnas 'revenue' y 'budget'.

In [69]:
movies['revenue'].value_counts()[0]

37949

In [70]:
movies['budget'].value_counts()[0]

36470

Se crea una variable que divide el valor de la columna 'revenue' por el valor de la columna 'budget' siempre que ambos valores sean mayores a cero.

In [71]:
return_movie = (
    lambda row: 
        row['revenue'] 
        / row['budget'] 
    if row['revenue'] > 0 
    and row['budget'] > 0 
    else 0)

Se crea la columna 'return' asignandole la anterior operación.

In [72]:
movies['return'] = movies.apply(
       return_movie, 
       axis=1).round(2)

La columna 'return' fue creada.

In [73]:
'return' in movies.columns

True

### Resetear el índice

El último índice es mayor a la cantidad de filas.

In [74]:
movies.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            45425, 45426, 45427, 45428, 45429, 45430, 45432, 45433, 45434,
            45435],
           dtype='int64', length=45346)

Se resetea el índice.

In [75]:
movies.reset_index(
    drop=True, 
    inplace=True)

El índice es igual a la cantidad de filas - 1.

In [76]:
movies.index

RangeIndex(start=0, stop=45346, step=1)

### Última revisión

In [77]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45346 entries, 0 to 45345
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             45346 non-null  int64
 1   movie_id           45346 non-null  object
 2   original_language  45335 non-null  object
 3   overview           44405 non-null  object
 4   popularity         45346 non-null  float64
 5   release_date       45346 non-null  object
 6   revenue            45346 non-null  int64
 7   runtime            45100 non-null  float64
 8   status             45266 non-null  object
 9   tagline            20387 non-null  object
 10  title              45346 non-null  object
 11  vote_average       45346 non-null  float64
 12  vote_count         45346 non-null  int64
 13  genres             45346 non-null  object
 14  release_year       45346 non-null  object
 15  return             45346 non-null  float64
dtypes: float64(4), int64(3), object(9)
memory usage: 5.5+ MB

## Carga

In [78]:
ruta_actual = os.getcwd()

ruta_actual

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\notebooks\\ETL'

In [79]:
ruta_del_proyecto = os.path.dirname(
    os.path.dirname(
        ruta_actual))

ruta_del_proyecto

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas'

In [80]:
ruta_a_exportar = os.path.join(
    ruta_del_proyecto, 
    'data', 
    'ETL', 
    'movies.parquet')

ruta_a_exportar

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\data\\ETL\\movies.parquet'

In [81]:
movies.to_parquet(ruta_a_exportar)

In [82]:
del movies
gc.collect()

144